# Qwen3-30B-A3B-Instruct MoE 配置文件 - 用于快速测试
input_max_length: 8192
datasets: ruler_niah_mk_2
generation_max_length: 50
test_files: data/ruler/niah_multikey_2/validation_8192.jsonl
demo_files: 
use_chat_template: true
max_test_samples: 3  # MoE模型运行较慢，先用少量样本测试
shots: 2
stop_new_line: false
model_name_or_path: /home/scratch.sarawang_ent/modelscope_cache/Qwen/Qwen3-30B-A3B-Instruct-2507
use_tgi_serving: false
